name: "Hadolint Github Action"
description: "A stable, well-tested, highly configurable way of checking your Dockerfile(s) with Hadolint"
author: "Johan Bergström <bugs@bergstroem.nu>"

inputs:
  dockerfile:
    default: "./Dockerfile"
    description: Path to Dockerfile(s). Accepts shell expansions (`**/Dockerfile`)
    required: true
  config_file:
    description: Path to optional config (hadolint defaults to read `./hadolint.yml` if it exists)
    required: false
  error_level:
    default: 0
    description: Fail CI based on hadolint output (`-1` never, `0` error, `1` warning, `2` info/style)
    required: false
  annotate:
    default: true
    description: Annotate code inline in the github PR viewer (`true`/`false`)
    required: true
  output_format:
    description: Output format (choose between `checkstyle`, `codeclimate`, `gitlab_codeclimate`, `json` or `tty`)
    required: false
  hadolint_path:
    description: Absolute path to hadolint binary. Left unset means it can be found in `$PATH`
    required: false
  version:
    default: 2.13.1
    description: Use a specific version of Hadolint
    required: true

outputs:
  hadolint_output:
    description: Optional output from Hadolint, controlled with `output_format`
    value: ${{ steps.run.outputs.hadolint_output }}
  hadolint_version:
    description: Hadolint version in use
    value: ${{ steps.run.outputs.hadolint_version }}
  hadolint_gh_action_version:
    description: hadolint-gh-action version in use
    value: ${{ steps.run.outputs.hadolint_gh_action_version }}

runs:
  using: composite
  steps:
    - name: Download hadolint and make it available in path
      shell: bash
      env:
        version: ${{ inputs.version }}
      run: ${{ github.action_path }}/install.sh

    - name: Invoke hadolint.sh
      id: run
      shell: bash
      env:
        dockerfile: ${{ inputs.dockerfile }}
        config_file: ${{ inputs.config_file }}
        error_level: ${{ inputs.error_level }}
        annotate: ${{ inputs.annotate }}
        output_format: ${{ inputs.output_format }}
        version: ${{ inputs.version }}
      run: ${{ github.action_path }}/hadolint.sh

branding:
  icon: "check"
  color: "green"
